name: AjaxSearch CI
on:
  push: { branches: [ main, master ] }
  pull_request: { branches: [ "**" ] }
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: { php: ['8.1','8.2'] }
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, json, curl, dom, gd, xml, zip
          tools: composer:v2
      - uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-
      - run: composer install --no-interaction --prefer-dist
      - name: Configure BASE_URL
        env: { BASE_URL: ${{ secrets.AJAXSEARCH_BASE_URL }} }
        run: |
          if [ -z "$BASE_URL" ]; then
            echo "::error::Set secret AJAXSEARCH_BASE_URL (e.g. https://dev.example.com)"
            exit 1
          fi
          mkdir -p tests/codeception
          printf "BASE_URL=%s\nSEARCH_QUERY=test\n" "$BASE_URL" > tests/codeception/.env
      - run: vendor/bin/codecept run -c tests/codeception/codeception.yml api --steps --verbosity 1
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeception-output-php-${{ matrix.php }}
          path: tests/codeception/_output
          if-no-files-found: ignore
